import type { OverlayConfig } from './types'

export const ARMOR_OVERLAY_REGISTRY: Record<string, OverlayConfig> = {
    'leather-vest': {
        walkTextureKey: 'armor_leather_torso_walk',
        walkAssetPath: 'assets/walkcycle/TORSO_leather_armor_torso.png',
        slashTextureKey: 'armor_leather_torso_slash',
        slashAssetPath: 'assets/slash/TORSO_leather_armor_torso.png',
        frameWidth: 64,
        frameHeight: 64,
        walkDirectionFrames:  { north: [1, 8], west: [10, 17], south: [19, 26], east: [28, 35] },
        slashDirectionFrames: { north: [0, 5], west: [6, 11], south: [12, 17], east: [18, 23] },
        walkFrameRate: 16,
        slashFrameRate: 24,
        hurtTextureKey: 'armor_leather_torso_hurt',
        hurtAssetPath:  'assets/hurt/TORSO_leather_armor_torso.png',
        hurtFrameRate:  12,
    },
    'plate-armor': {
        walkTextureKey:  'armor_plate_torso_walk',
        walkAssetPath:   'assets/walkcycle/TORSO_plate_armor_torso.png',
        slashTextureKey: 'armor_plate_torso_slash',
        slashAssetPath:  'assets/slash/TORSO_plate_armor_torso.png',
        frameWidth:  64,
        frameHeight: 64,
        walkDirectionFrames:  { north: [1, 8], west: [10, 17], south: [19, 26], east: [28, 35] },
        slashDirectionFrames: { north: [0, 5], west: [6, 11], south: [12, 17], east: [18, 23] },
        walkFrameRate:  16,
        slashFrameRate: 24,
        hurtTextureKey: 'armor_plate_torso_hurt',
        hurtAssetPath:  'assets/hurt/TORSO_plate_armor_torso.png',
        hurtFrameRate:  12,
    },
    'chain-armor': {
        walkTextureKey:  'armor_chain_torso_walk',
        walkAssetPath:   'assets/walkcycle/TORSO_chain_armor_torso.png',
        slashTextureKey: 'armor_chain_torso_slash',
        slashAssetPath:  'assets/slash/TORSO_chain_armor_torso.png',
        frameWidth:  64,
        frameHeight: 64,
        walkDirectionFrames:  { north: [1, 8], west: [10, 17], south: [19, 26], east: [28, 35] },
        slashDirectionFrames: { north: [0, 5], west: [6, 11], south: [12, 17], east: [18, 23] },
        walkFrameRate:  16,
        slashFrameRate: 24,
        hurtTextureKey: 'armor_chain_torso_hurt',
        hurtAssetPath:  'assets/hurt/TORSO_chain_armor_torso.png',
        hurtFrameRate:  12,
    },
    'purple-jacket': {
        walkTextureKey:  'armor_purple_jacket_walk',
        walkAssetPath:   'assets/walkcycle/TORSO_chain_armor_jacket_purple.png',
        slashTextureKey: 'armor_purple_jacket_slash',
        slashAssetPath:  'assets/slash/TORSO_chain_armor_jacket_purple.png',
        frameWidth:  64,
        frameHeight: 64,
        walkDirectionFrames:  { north: [1, 8], west: [10, 17], south: [19, 26], east: [28, 35] },
        slashDirectionFrames: { north: [0, 5], west: [6, 11], south: [12, 17], east: [18, 23] },
        walkFrameRate:  16,
        slashFrameRate: 24,
        hurtTextureKey: 'armor_purple_jacket_hurt',
        hurtAssetPath:  'assets/hurt/TORSO_chain_armor_jacket_purple.png',
        hurtFrameRate:  12,
    },
    'robe': {
        walkTextureKey:  'armor_robe_walk',
        walkAssetPath:   'assets/walkcycle/TORSO_robe_shirt_brown.png',
        slashTextureKey: 'armor_robe_slash',
        slashAssetPath:  'assets/slash/TORSO_robe_shirt_brown.png',
        frameWidth:  64,
        frameHeight: 64,
        walkDirectionFrames:  { north: [1, 8], west: [10, 17], south: [19, 26], east: [28, 35] },
        slashDirectionFrames: { north: [0, 5], west: [6, 11], south: [12, 17], east: [18, 23] },
        walkFrameRate:  16,
        slashFrameRate: 24,
        hurtTextureKey: 'armor_robe_hurt',
        hurtAssetPath:  'assets/hurt/TORSO_robe_shirt_brown.png',
        hurtFrameRate:  12,
    },
    'white-shirt': {
        walkTextureKey:  'armor_white_shirt_walk',
        walkAssetPath:   'assets/walkcycle/TORSO_leather_armor_shirt_white.png',
        slashTextureKey: 'armor_white_shirt_slash',
        slashAssetPath:  'assets/slash/TORSO_leather_armor_shirt_white.png',
        frameWidth:  64,
        frameHeight: 64,
        walkDirectionFrames:  { north: [1, 8], west: [10, 17], south: [19, 26], east: [28, 35] },
        slashDirectionFrames: { north: [0, 5], west: [6, 11], south: [12, 17], east: [18, 23] },
        walkFrameRate:  16,
        slashFrameRate: 24,
        hurtTextureKey: 'armor_white_shirt_hurt',
        hurtAssetPath:  'assets/hurt/TORSO_leather_armor_shirt_white.png',
        hurtFrameRate:  12,
    }
}
